cargo-features = ["profile-rustflags"]

[package]
name = "petty-chess"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
atoi = "2.0.0"
bitflags = "2.6.0"
clap = { version = "4.5.25", features = ["derive"] }
derive-try-from-primitive = "1.0.0"
serde = { version = "1.0.217", optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-appender = { version = "0.2.3", optional = true }
tracing-subscriber = { version = "0.3.18", default-features = false, optional = true, features = [
    "fmt",
    "smallvec",
    "std",
] }

[features]
default = ["tracing"]
tracing = ["dep:tracing", "dep:tracing-appender", "dep:tracing-subscriber"]
serde = ["dep:serde"]

[profile.dev]
opt-level = 3
panic = "abort"
debug = false

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
rustflags = ["-Ctarget-cpu=native"]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_lossless = "allow"
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
missing_panics_doc = "allow"
